name: complex
on: push

jobs:
  ubuntu: 
    runs-on: ubuntu-latest
    steps:
    - run: date
  window: 
      runs-on: windows-latest
      steps:
      - run: date
  macos: 
      runs-on: macos-latest
      steps:
      - run: date
  ubuntudepends: 
      #needs:[ubuntu, windows, macos]
      runs-on: ubuntu-latest
      steps:
      - run: date
